version: '3.7'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mdillon/postgis:10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=415263
      - POSTGRES_DB=mydb
  celery:
    build: ./
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: celery -A spider worker -B -l INFO
    volumes:
      - ./:/usr/src/app
    depends_on:
      - web
      - redis
  redis:
    image: redis
    restart: always
    command: redis-server