# Generated by Django 3.0 on 2020-10-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
