# Generated by Django 3.0 on 2020-10-06 16:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(blank=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name="Местоположение{'latitude': 0, 'longitude': 0}"),
        ),
    ]
