# Generated by Django 3.0 on 2020-10-06 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201006_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Местоположение'),
        ),
    ]
